-- PC INVENTORY V2
-- این مهاجرت داده های inventory فعلی را حذف نمی کند.
-- قبل از اجرا از دیتابیس بکاپ بگیرید.

create extension if not exists pgcrypto;

alter table public.inventory add column if not exists version integer not null default 1;
alter table public.inventory add column if not exists updated_at timestamptz not null default now();
alter table public.inventory add column if not exists updated_by uuid;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null,
  login_email text unique not null,
  permissions jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.app_config (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('categories','brands','owners')),
  value text not null,
  created_at timestamptz not null default now(),
  unique(type,value)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);

alter table public.inventory enable row level security;
alter table public.profiles enable row level security;
alter table public.app_config enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.has_permission(p text)
returns boolean language sql stable security definer set search_path=public
as $$
  select coalesce((select active and coalesce((permissions ->> p)::boolean,false) from public.profiles where id=auth.uid()),false);
$$;

revoke all on function public.has_permission(text) from public, anon;
grant execute on function public.has_permission(text) to authenticated;

drop policy if exists inventory_public_read on public.inventory;
create policy inventory_public_read on public.inventory for select to anon, authenticated using (true);

drop policy if exists inventory_insert on public.inventory;
create policy inventory_insert on public.inventory for insert to authenticated with check (public.has_permission('create_item'));

drop policy if exists inventory_update on public.inventory;
create policy inventory_update on public.inventory for update to authenticated using (public.has_permission('edit_item') or public.has_permission('change_price') or public.has_permission('change_quantity')) with check (public.has_permission('edit_item') or public.has_permission('change_price') or public.has_permission('change_quantity'));

drop policy if exists inventory_delete on public.inventory;
create policy inventory_delete on public.inventory for delete to authenticated using (public.has_permission('delete_item'));

drop policy if exists config_public_read on public.app_config;
create policy config_public_read on public.app_config for select to anon, authenticated using (true);
drop policy if exists config_manage on public.app_config;
create policy config_manage on public.app_config for all to authenticated using (public.has_permission('manage_config')) with check (public.has_permission('manage_config'));

drop policy if exists profiles_self_or_admin on public.profiles;
create policy profiles_self_or_admin on public.profiles for select to authenticated using (id=auth.uid() or public.has_permission('manage_admins'));

drop policy if exists logs_admin_read on public.audit_logs;
create policy logs_admin_read on public.audit_logs for select to authenticated using (public.has_permission('view_logs'));

-- actor id can be filled by a trigger without exposing an insert policy to clients.
create or replace function public.audit_inventory_change()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  if tg_op='INSERT' then
    insert into public.audit_logs(actor_id,action,entity_id,details) values(auth.uid(),'INSERT',new.id::text,jsonb_build_object('after',to_jsonb(new)));
    return new;
  elsif tg_op='UPDATE' then
    insert into public.audit_logs(actor_id,action,entity_id,details) values(auth.uid(),'UPDATE',new.id::text,jsonb_build_object('before',to_jsonb(old),'after',to_jsonb(new)));
    return new;
  else
    insert into public.audit_logs(actor_id,action,entity_id,details) values(auth.uid(),'DELETE',old.id::text,jsonb_build_object('before',to_jsonb(old)));
    return old;
  end if;
end;
$$;

drop trigger if exists inventory_audit_trigger on public.inventory;
create trigger inventory_audit_trigger after insert or update or delete on public.inventory for each row execute function public.audit_inventory_change();

-- نسخه قبلی داده ها را دست نمی زند؛ فقط برای Realtime آماده می کند.
alter table public.inventory replica identity full;

-- مقادیر پیش فرض فقط در صورت نبودن اضافه می شوند.
insert into public.app_config(type,value) values
('categories','کارت گرافیک'),('categories','سی‌پی‌یو (CPU)'),('categories','رم (RAM)'),('categories','مادربورد'),('categories','پاور'),('categories','کیس'),('categories','فن سی‌پی‌یو'),('categories','سایر'),
('brands','ASUS'),('brands','MSI'),('brands','GIGABYTE'),('brands','Corsair'),('brands','Intel'),('brands','AMD'),('brands','Green'),('brands','Cooler Master'),('brands','سایر'),
('owners','مجموعه'),('owners','میلاد'),('owners','محسن'),('owners','علی'),('owners','شخص حقیقی')
on conflict(type,value) do nothing;

-- اگر inventory قبلاً در publication نیست، اضافه اش کنید.
do $$ begin
  begin
    alter publication supabase_realtime add table public.inventory;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.app_config;
  exception when duplicate_object then null;
  end;
end $$;

-- نکته: اولین مدیر را با Edge Function بسازید؛ service_role هرگز در فرانت قرار نمی گیرد.

-- امنیت مهم: کاربری که فقط اجازه تغییر قیمت/موجودی دارد نباید بتواند ستون های دیگر را دستکاری کند.
create or replace function public.enforce_inventory_field_permissions()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  if public.has_permission('edit_item') then return new; end if;
  if not public.has_permission('change_price') and new.price is distinct from old.price then
    raise exception 'PERMISSION_DENIED_PRICE';
  end if;
  if not public.has_permission('change_quantity') and new.quantity is distinct from old.quantity then
    raise exception 'PERMISSION_DENIED_QUANTITY';
  end if;
  if new.category is distinct from old.category or new.brand is distinct from old.brand or new.model is distinct from old.model
     or new.unit is distinct from old.unit or new.owner_type is distinct from old.owner_type
     or new.item_condition is distinct from old.item_condition or new.warranty is distinct from old.warranty
     or new.description is distinct from old.description then
    raise exception 'PERMISSION_DENIED_FIELDS';
  end if;
  return new;
end;
$$;

drop trigger if exists inventory_permission_trigger on public.inventory;
create trigger inventory_permission_trigger before update on public.inventory for each row execute function public.enforce_inventory_field_permissions();
